#Note: this program was writen using github copilots ghost writing feature by writing a text prompt
#to describe the functionality of the desired functions i wanted to create. 

#Prompts:

#implement a function called calculate_flight_time that takes weight in grams(weight_grams).
#It returns active flight time in minuits for a given payloads weight using this formula, 
# T(w) = 180 - 0.1w. T is resulting active flight time in minuits and w is payload weight in
#grams, which must be greater than or equal to 0 grams. if the formula produces a negative value,
#return 0, if weight_grams is less than 0, raise a ValueError with the message "Weight must be 
#greater than or equal to 0 grams."

#create a function called flight_time_table that takes in max weight in grams(max_weight_grams),
#and step_grams. the function returns a list of (weight, flight_time) pairs for payload weights
#from 0 up to and including max_weight_grams, in increments of step_grams. the function must internally
#call calculate_flight_time() for each weight rather than recalculating the formula

def calculate_flight_time(weight_grams):
    """Calculates active flight time in minuits for a given payload weight in grams
    
    Arguments:
        weight_grams: The added weight in grams.

    Returns:
        flight_time: the estimated flight time in minuits
    
    """

    if weight_grams < 0:
        raise ValueError("Weight must be greater than or equal to 0 grams.")

    #EDIT -- copilot suggested a random formula here instead of the one provided in the prompt,
    #so i had to correct and edit it myself.
    flight_time = 180 - 0.1 * weight_grams
    return max(0, flight_time)


##ACCEPT -- after learning my lesson with the first function with github copilot writing random
#code, i decided to write a very detailed prompt for the first and second functions. After being
#very detailed and specific with the prompt, the code generated by github copilot was correct and
#passed all tests generated in the test_flight_calculator.py file.
def flight_time_table(max_weight_grams, step_grams):
    """returns a list of (weight, flight_time) pairs for payload weights from 0 to including
    the max weight of the payload, in increments of step_grams.
    
    Arguments:
        max_weight_grams: The maximum weight in grams.
        step_grams: amount of grams being incremented for each entry.
        
    Returns:
        table: a list of (weight, flight_time) pairs"""
    
    table = []
    for weight in range(0, max_weight_grams + 1, step_grams):
        flight_time = calculate_flight_time(weight)
        table.append((weight, flight_time))
    return table

