#REJECT -- when the github copilot chat feature generated this code for testing, it imported this
#module which is pytest, but the pytest module wasnt even installed, which is why it wasnt working at first.
#it was only after i installed the pytest module that the code worked and passed all tests. 
import pytest

from flight_calculator import calculate_flight_time, flight_time_table

#AUTHOR: Carlos Gonzalez, with the assistance of github copilot chat feature and chatgpt.

# AI_USE NOTE:
#code generated by github copilot chat feature was tested by me personally by running pytest, using the command
# -m pytest -v in the terminal. the code passed 17 out of 17 tests.

class TestCalculateFlightTime:
    @pytest.mark.parametrize(
        "weight_grams, expected",
        [
            (0, 180.0),
            (50, 175.0),
            (100, 170.0),
            (250, 155.0),
            (1000, 80.0),
        ],
    )
    def test_calculate_flight_time_normal_inputs(self, weight_grams, expected):
        assert calculate_flight_time(weight_grams) == pytest.approx(expected)

    @pytest.mark.parametrize(
        "weight_grams, expected",
        [
            (1800, 0.0),
            (2000, 0.0),
            (5000, 0.0),
        ],
    )
    def test_calculate_flight_time_clamps_to_zero(self, weight_grams, expected):
        assert calculate_flight_time(weight_grams) == pytest.approx(expected)

    def test_calculate_flight_time_zero_boundary(self):
        assert calculate_flight_time(0) == pytest.approx(180.0)

    @pytest.mark.parametrize("weight_grams", [-1, -0.1, -1000])
    def test_calculate_flight_time_negative_input_raises_value_error(self, weight_grams):
        with pytest.raises(ValueError, match="Weight must be greater than or equal to 0 grams."):
            calculate_flight_time(weight_grams)


class TestFlightTimeTable:
    def test_flight_time_table_normal_inputs(self):
        table = flight_time_table(10, 2)
        expected = [
            (0, 180.0),
            (2, 179.8),
            (4, 179.6),
            (6, 179.4),
            (8, 179.2),
            (10, 179.0),
        ]

        assert len(table) == len(expected)
        for (actual_weight, actual_time), (expected_weight, expected_time) in zip(table, expected):
            assert actual_weight == expected_weight
            assert actual_time == pytest.approx(expected_time)

    def test_flight_time_table_includes_zero_and_max_weight(self):
        table = flight_time_table(3, 1)
        expected = [
            (0, 180.0),
            (1, 179.9),
            (2, 179.8),
            (3, 179.7),
        ]

        assert table == pytest.approx(expected, rel=1e-9)

    def test_flight_time_table_boundary_clamps_at_zero(self):
        table = flight_time_table(1800, 300)
        expected = [
            (0, 180.0),
            (300, 150.0),
            (600, 120.0),
            (900, 90.0),
            (1200, 60.0),
            (1500, 30.0),
            (1800, 0.0),
        ]

        assert len(table) == len(expected)
        for (actual_weight, actual_time), (expected_weight, expected_time) in zip(table, expected):
            assert actual_weight == expected_weight
            assert actual_time == pytest.approx(expected_time)

    @pytest.mark.parametrize(
        "max_weight_grams, step_grams, expected",
        [
            (-5, 2, []),
            (10, -2, []),
            (10, 0, ValueError),
        ],
    )
    def test_flight_time_table_boundary_and_invalid_step_cases(self, max_weight_grams, step_grams, expected):
        if expected is ValueError:
            with pytest.raises(ValueError, match=r"range\(\) arg 3 must not be zero"):
                flight_time_table(max_weight_grams, step_grams)
        else:
            assert flight_time_table(max_weight_grams, step_grams) == expected